### ISSUE TITLE
backpressure for matching topics?

### ISSUE THREAD

**Issue by behrad** [mcollina/aedes-cached-persistence#5]
Does it help if we change [this](https://github.com/mcollina/aedes-cached-persistence/blob/master/index.js#L130) to a streamable one? Does it provide back pressure when publishing a message to a wildcard topic with too many subscribers @mcollina ?

**Comment by mcollina** [comment]
The problem is that the cost is already paid, which is in the creation big array. Even if it is streamable, it will not help as the data structure as already been allocated. However, we can change https://github.com/mcollina/aedes/blob/e347031544512f23999a54df4debdae08628d5b1/aedes.js#L194-L196 to be a queue and not act on all of them in parallel.

**Comment by behrad** [comment]
https://github.com/mcollina/aedes/pull/131
